### ISSUE TITLE
Reduced gas cost compared to what?

### ISSUE THREAD

**Issue by paulrberg** [wighawag/clones-with-immutable-args#13]
I've just stumbled upon this project - while reading the README, I stopped at this part:

> By doing so, the gas cost of creating clones is **reduced**, since there's no need to store the immutable arguments in storage.

Reduced compared to what? [EIP-1167](https://eips.ethereum.org/EIPS/eip-1167) proxies?

I think that it would be worth it to clarify this in the README.

**Comment by wighawag** [comment]
Thanks @paulrberg for the feedback

It won't be cheaper than EIP-1167 if you need exact copies clone, but the story is different as soon as you need to parameterise a clone. 

With EIP-1167 you ll need to do so by assigning some storage variable

With clones-with-immutable, you can parametrise your clone directly in the bytecode, saving you from using storage and so even reading the param is cheaper .

So if you know you are not gonna need parametrization, then you can keep using EIP-1967, otherwise, clones-with-immutables is cheaper

I ll see how I can clarify that in the README

**Comment by wighawag** [comment]
I added some clarifications in the README, let me know what you think

**Comment by paulrberg** [comment]
Great explanation. Thanks! The README looks good now.

**Comment by caoyifeng007** [comment]
Hi @wighawag, I have same confusion as PaulRBerg, could you show me an use case of EIP1167 that parameterise a clone using storage.
